<?php
/**
 * Created by PhpStorm.
 * User: dmitry
 * Date: 02.10.18
 * Time: 13:47
 */

namespace App\Facades;

use Illuminate\Support\Facades\Facade;

class StatusCode extends Facade
{
    protected static function getFacadeAccessor()
    {
        // TODO: Change the autogenerated stub
        return 'StatusCode';
    }
}